title: Live A Hero Wiki
url: https://liveahero-wiki.github.io
github_edit: https://github.com/liveahero-wiki/liveahero-wiki.github.io/edit/master
permalink: /news/:year/:month/:title/
markdown: kramdown
kramdown:
  parse_block_html: true
sass:
  style: compressed
plugins:
  #- jekyll-feed
  - jekyll-redirect-from
  - jemoji
defaults:
  - scope:
      path: ""
    values:
      layout: default
  - scope:
      type: "heroes"
    values:
      layout: heroes
  - scope:
      path: "assets/img/hero_sprites"
    values:
      hero_sprites: true

collections:
  heroes:
    output: true
    permalink: /:collection/:path/
